-module(achievement_definitions).
-export([
    all/0
    ]).

-spec all() -> Achievements::list(achievement:achievement()).
all() ->
    [
    {<<"8th Wonder">>,
     <<"Win a bonus hand with at least 8 Honba (bonus counters) are in play">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"A Walk in the Woods">>,<<"Score a Bamboo Full-Flush">>,<<"noimg.png">>, <<"">>, []},
    {<<"Adoptive Parent">>,<<"Score a Thirteen Orphans">>,<<"noimg.png">>, <<"">>, []},
    {<<"Against a Common Enemy">>,<<"Take part in a Double Ron">>,<<"noimg.png">>, <<"">>, []},
    {<<"All Green!">>,<<"Score a Green Hand">>,<<"noimg.png">>, <<"">>, []},
    {<<"Blitzkrieg">>,<<"Score Double Riichi and One-Shot in the same hand">>,
     <<"noimg.png">>, <<"">>, [<<"O Hai, I'm in Tenpai!">>, <<"Ludicrous Speed">>]},
    {<<"Bowling Alley">>,<<"Score a Circles Full-Flush">>,<<"noimg.png">>, <<"">>, []},
    {<<"Can't Hold all These Doras (Rank 1)">>,
     <<"Win a hand with 6 or more Doras (Red Doras and Hidden Doras count too)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Can't Hold all These Doras (Rank 2)">>,
     <<"Win a hand with 9 or more Doras (Red Doras and Hidden Doras count too)">>,
     <<"noimg.png">>, <<"">>, [<<"Can't Hold all These Doras (Rank 1)">>]},
    {<<"Can't Hold all These Doras (Rank 3)">>,
     <<"Win a hand with 12 or more Doras (Red Doras and Hidden Doras count too)">>,
     <<"noimg.png">>, <<"">>, [<<"Can't Hold all These Doras (Rank 2)">>]},
    {<<"Crash Course">>,
     <<"Force an abortive draw by declaring the fourth Riichi">>,<<"noimg.png">>, <<"">>, []},
    {<<"D I S C O N N E C T E D">>,
     <<"Open an initial hand with no pairs, triples, quadruples nor two contiguous tiles in the same suit (brotip: take a screenshot of the hand to claim the achivement at the end of hand and keep on playing)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Deja Vu">>,
     <<"Call twice the same tile to complete two identical Chows in a single game">>,
     <<"noimg.png">>, <<"A déjà vu is usually a glitch in the Matrix. It happens when they chi something.">>, []},
    {<<"Delusions of Victory">>,
     <<"Declare a false Ron and pay a chombo penalty for it">>,<<"noimg.png">>, <<"LOL JK!!11!!one!">>, []},
    {<<"Die Hard">>,
     <<"Terminate a game with less than 1000 points (before applying winner bonuses)">>,
     <<"noimg.png">>, <<"It's just a flesh wound.">>, []},
    {<<"Dragon Trainer">>,<<"Score a Little Three Dragons">>,<<"noimg.png">>, <<"">>, []},
    {<<"Fanpaistic!">>,
     <<"Call a Fanpai Pon during the first uninterrupted go-round.">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Four o' Four">>,<<"Force an abortive draw by calling the fourth Kan">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Grenadier">>,
     <<"Reduce two opponents' points below zero with a single Tsumo">>,
     <<"noimg.png">>, <<"">>, [<<"Shot on the Crowd">>]},
    {<<"Han Solo">>,
     <<"Win waiting for a 1-out Character tile (to determine the outs only tiles visible to the player counts. This means open melds, Dora indicators, the river and own's hand)">>,
     <<"noimg.png">>, <<"Great shot, kid, that was one in a million!">>, [<<"Hell Wait">>]},
    {<<"Hell Wait">>,
     <<"Win a hand with a 1-out wait (to determine the outs only tiles visible to the player counts. This means open melds, Dora indicators, the river and own's hand)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"I Have an Encoding Problem!">>,
     <<"Win with a hand composed entirely of Pairs/Pons/Kans of either Characters tiles or White Dragons, then declare BEGINNING OF COSMOS!">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"I Run an Orphanage">>,
     <<"Score a Thirteen Orphans on a thirteen-sided wait">>,<<"noimg.png">>, <<"">>, [<<"Adoptive Parent">>]},
    {<<"I'll Do It Myself!">>,
     <<"Score a Riichi while being Furiten (Temporarily Furiten counts, too)">>,
     <<"noimg.png">>, <<"">>, [<<"Thanks for Nothing">>]},
    {<<"I'm On Fire!">>,<<"Stay east for 5 consecutive hands">>,<<"noimg.png">>, <<"">>, []},
    {<<"In the Eye of the Storm">>,<<"Score a Big Four Winds">>,<<"noimg.png">>, <<"">>, []},
    {<<"Invisible">>,
     <<"Terminate a Hanchan (East-South match) without any of your tiles being called">>,
     <<"noimg.png">>, <<"">>, [<<"Lack of Presence">>]},
    {<<"It Is (Not) Alone">>,
     <<"Win on a pair wait on the last closed tile in your hand">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"It Looks Easier From the Outside">>,
     <<"Score a Pinfu">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Kan I Win?">>,<<"Score an After a Kong">>,<<"noimg.png">>, <<"">>, []},
    {<<"Kan Not">>,<<"Discard four times the same tile in a single game">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Keep it Simple">>,<<"Score a Tanyao">>,<<"noimg.png">>, <<"">>, []},
    {<<"King of the Mountain">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of +140 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 10)">>]},
    {<<"Lack of Presence">>,
     <<"Terminate either a Tonpuusen (East-Only match) or the East hand of an Hanchan (East-South match) without any of your tiles being called">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Last Airbender">>,<<"Score a Little Four Winds">>,<<"noimg.png">>, <<"">>, []},
    {<<"Literate">>,<<"Score a Characters Full-Flush">>,<<"noimg.png">>, <<"">>, []},
    {<<"Little Mermaid">>,<<"Score a Bottom of the Sea">>,<<"noimg.png">>, <<"">>, []},
    {<<"Ludicrous Speed">>,<<"Score a One-Shot">>,<<"noimg.png">>, <<"">>, []},
    {<<"Mother of Dragons">>,<<"Score a Big Three Dragons">>,<<"noimg.png">>, <<"">>, []},
    {<<"Nine Etched Fails">>,
     <<"Force an abortive draw by having 9 or more different orphans on the opening hand">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"No Pain, No Gain">>,
     <<"Terminate a full game (either East-South or East-only) with a result of +-0 after awarding the winner bonuses">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Nuke From Orbit">>,
     <<"Reduce three opponents' points below zero with a single tsumo">>,
     <<"noimg.png">>, <<"Nuclear launch detected.">>, [<<"Grenadier">>]},
    {<<"O Hai, I'm in Tenpai!">>,<<"Score a Double Riichi">>,<<"noimg.png">>, <<"">>, []},
    {<<"Oath of Allegiance">>,<<"Participate in a Triple Ron">>,<<"noimg.png">>, <<"">>, []},
    {<<"One Shot One Kill">>,
     <<"Reduce an opponent that had 25000 or more points at the beginning of the match to zero points with a direct hit">>,
     <<"noimg.png">>, <<"">>, [<<"Player Killer">>]},
    {<<"Out of Reach">>,
     <<"Call a Ron on the Riichi declaration tile of another player">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Pick a Seaweed From the Bottom of the Ocean">>,
     <<"Score Bottom of the Sea and After a Kan in the same game">>,
     <<"noimg.png">>, <<"">>, [<<"Kan I Win?">>, <<"Little Mermaid">>]},
    {<<"Ping Pon">>,
     <<"Have two players call four consecutive Pons from each other (awarded to both)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Pinterest">>,
     <<"Call 4 or more Circle tiles from your opponents in a single game">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Player Killer">>,
     <<"Reduce an opponent's points below zero with a direct hit">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Sanpei">>,<<"Score a Bottom of the River">>,<<"noimg.png">>, <<"">>, []},
    {<<"Save the Children From The Bad Guys">>,
     <<"Score a Thirteen Orphans robbing a closed Kan">>,<<"noimg.png">>, <<"">>, [<<"Adoptive Parent">>]},
    {<<"Save Tsumonday!">>,<<"Play your first game">>,<<"noimg.png">>, <<"">>, []},
    {<<"Seventh Son of a Seventh Tile">>,<<"Score a Seven Pairs">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Shot on the Crowd">>,
     <<"Reduce an opponent's points below zero with a Tsumo">>,<<"noimg.png">>, <<"">>, [<<"Player Killer">>]},
    {<<"Siberian Express">>,
     <<"Win with a Circle Nine Gates. You must shout SIBERIAN EXPRESS! while striking an epic pose">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Strong">>,<<"Win a game with 1 pung of ",226,145,168," in your hand (open or closed)">>,
     <<"noimg.png">>, <<"I'm a strong fairy!">>, []},
    {<<"Stronger">>,
     <<"Win a game with 2 pungs of ",226,145,168," in your hand (open or closed)">>,
     <<"noimg.png">>, <<"I'm a stronger fairy!">>, [<<"Strong">>]},
    {<<"Strongest">>,
     <<"Win a game with 3 pungs of ",226,145,168," in your hand (open or closed)">>,
     <<"noimg.png">>, <<"I'm the strongest fairy in the world!">>, [<<"Stronger">>, <<"Strong">>]},
    {<<"Strongester">>,
     <<"Win a game with 1 kong of ",226,145,168," in your hand (open or closed)">>,
     <<"noimg.png">>, <<"I'm the strongester fairy in the world!">>, [<<"Strong">>]},
    {<<"Strongestest">>,
     <<"Win a game with 2 kongs of ",226,145,168," in your hand (open or closed)">>,
     <<"noimg.png">>, <<"I'm the strongestest fairy in the world!">>, [<<"Strongester">>, <<"Stronger">>, <<"Strong">>]},
    {<<"Strongestestest">>,
     <<"Win a game with 3 kongs of ",226,145,168," in your hand (open or closed)">>,
     <<"noimg.png">>, <<"I'm the strongestestest fairy in the world!">>, [<<"Strongestest">>, <<"Strongester">>, <<"Strongest">>, <<"Stronger">>, <<"Strong">>]},
    {<<"Superman">>,
     <<"Terminate a full game (either East-South or East-Only) without losing a single point (losing Riichi bets counts, too)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Thanks for Nothing">>,<<"Score a Fully Concealed Tsumo">>,<<"noimg.png">>, <<"">>, []},
    {<<"They See Me Ronning, They Hatin'">>,
     <<"Declare three consecutive Rons from three different players">>,
     <<"noimg.png">>, <<"Haters gonna hate.">>, []},
    {<<"Tiles Are Red, Violets Are Blue...">>,
     <<"Win with all three Red Doras and all four Red Dragons">>,<<"noimg.png">>, <<"">>, []},
    {<<"To the Top (Rank 1)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +30 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"To the Top (Rank 2)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +40 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 1)">>]},
    {<<"To the Top (Rank 3)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +50 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 2)">>]},
    {<<"To the Top (Rank 4)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +60 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 3)">>]},
    {<<"To the Top (Rank 5)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +70 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 4)">>]},
    {<<"To the Top (Rank 6)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +80 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 5)">>]},
    {<<"To the Top (Rank 7)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +90 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 6)">>]},
    {<<"To the Top (Rank 8)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +100 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 7)">>]},
    {<<"To the Top (Rank 9)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +110 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 8)">>]},
    {<<"To the Top (Rank 10)">>,
     <<"Terminate a full game (either East-South or East-Only) with a score of at least +120 points (after awarding winner bonuses)">>,
     <<"noimg.png">>, <<"">>, [<<"To the Top (Rank 9)">>]},
    {<<"Unlucky Fourth Object">>,
     <<"Force an abortive draw by discarding the fourth same wind in the first round">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Unriichiable">>,
     <<"Declare a Riichi with a 0-out wait (to determine the outs only tiles visible to the player counts. This means open melds, Dora indicators, the river and own's hand)">>,
     <<"noimg.png">>, <<"">>, []},
    {<<"Vulgar Display of Power">>,
     <<"Take precedence of a Chi/Pon declaration with a Pon/Ron declaration">>,
     <<"noimg.png">>, <<"">>, []}
    ].